### ISSUE TITLE
parser.js throws "Cannot read property 'toString' of undefined" error

### ISSUE THREAD

**Issue by greaturchin** [Swaagie/stackexchange#17]
I am trying to use the basic questions method and keep getting the error below. I can see that the API call successfully returns a buffer, but somewhere in the parser it gets lost and throws an error.

```
TypeError: Cannot read property 'toString' of undefined
    at Unzipped [as cb] (C:\...\node_modules\stackexchange\lib\parser.js:14:39)
    at Unzip.zlibBufferOnError (zlib.js:113:8)
    at Unzip.emit (events.js:198:13)
    at Zlib.zlibOnError [as onerror] (zlib.js:167:8)
```

**Comment by Trott** [comment]
Can you provide a code sample that generates this error for you?
